<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="2" failures="0" skipped="0" tests="2" time="0.250" timestamp="2024-07-15T15:24:29.087903" hostname="soraR"><testcase classname="" name="test_dir.test_baidu" time="0.000"><error message="collection failure">ImportError while importing test module 'D:\Projects\Selenium3Learn\pyautoTest\test_dir\test_baidu.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Users\Soral\anaconda3\Lib\importlib\__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_dir\test_baidu.py:12: in &lt;module&gt;
    from page.baidu_page import BaiduPage
page\baidu_page.py:1: in &lt;module&gt;
    from poium import Page, Element
C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\poium\__init__.py:20: in &lt;module&gt;
    from .webdriver import Page
C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\poium\webdriver.py:8: in &lt;module&gt;
    from appium.webdriver.common.touch_action import TouchAction as MobileTouchAction
E   ModuleNotFoundError: No module named 'appium.webdriver.common.touch_action'</error></testcase><testcase classname="pytest" name="internal" time="0.000"><error message="internal error">Traceback (most recent call last):
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\_pytest\main.py", line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
                         ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\_pytest\main.py", line 322, in _main
    config.hook.pytest_collection(session=session)
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\pluggy\manager.py", line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
                                                         ^^^^^^^^^^^^^^^
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\_pytest\main.py", line 333, in pytest_collection
    session.perform_collect()
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\_pytest\main.py", line 634, in perform_collect
    self.items.extend(self.genitems(node))
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\_pytest\main.py", line 812, in genitems
    node.ihook.pytest_collectreport(report=rep)
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\pluggy\manager.py", line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
                                                         ^^^^^^^^^^^^^^^
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\pytest_html\plugin.py", line 750, in pytest_collectreport
    self.append_failed(report)
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\pytest_html\plugin.py", line 465, in append_failed
    self._appendrow("Error", report)
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\pytest_html\plugin.py", line 433, in _appendrow
    result = self.TestResult(outcome, report, self.logfile, self.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\pytest_html\plugin.py", line 199, in __init__
    self.config.hook.pytest_html_results_table_row(report=report, cells=cells)
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\pluggy\manager.py", line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
                                                         ^^^^^^^^^^^^^^^
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\Soral\AppData\Local\pypoetry\Cache\virtualenvs\pyautotest-588KsMkE-py3.12\Lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Selenium3Learn\pyautoTest\conftest.py", line 27, in pytest_html_results_table_row
    cells.insert(2, html.td(report.description))
                            ^^^^^^^^^^^^^^^^^^
AttributeError: 'CollectReport' object has no attribute 'description'</error></testcase></testsuite></testsuites>